package com.l299l.newbedwars.arena;

import com.l299l.newbedwars.arena.gamerules.Gamerules;
import com.l299l.newbedwars.arena.generators.Generator;
import com.l299l.newbedwars.arena.generators.GeneratorType;
import com.l299l.newbedwars.arena.generators.leveling.GeneratorLeveling;
import com.l299l.newbedwars.arena.phases.GamePhases;
import com.l299l.newbedwars.arena.player.GamePlayer;
import com.l299l.newbedwars.arena.setup.Setup;
import com.l299l.newbedwars.arena.shops.TeamShop;
import com.l299l.newbedwars.arena.shops.TeamUpgrades;
import com.l299l.newbedwars.arena.team.Team;
import com.l299l.newbedwars.gui.GuiSave;
import org.bukkit.ChatColor;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.entity.Player;

import java.util.*;

public interface IArena {
    void start();
    void stop();
    boolean rollback();
    Integer getGameTime();
    void upgradeGenerators(GeneratorType type, Integer level);
    boolean join(Player player);
    boolean joinParty(List<Player> partyMembers);
    boolean rejoin(Player player);
    void leave(Player player);
    Boolean isPlayerInArena(Player player);
    Set<UUID> getPlayers();
    GamePlayer getPlayer(UUID player);
    void killPlayer(Player player);
    void cancelStart();
    void broadcast(String message);
    void broadcast(String message, HashMap<String, String> replace);
    void broadcastTitle(String title, String subtitle, Integer fadeIn, Integer stay, Integer fadeOut);
    World getArenaWorld();
    void enable();
    void disable();
    void setGamePhases(GamePhases gamePhases);
    String getNextGamePhase();
    String getCurrentGamePhase();
    void nextPhase();
    void advancePhase();
    int getPhaseTime();
    void setPhaseTime(int time);
    Boolean isEnabled();
    Boolean canBeEnabled();
    Boolean canBeDisabled();
    GameStatus status();
    Integer getMinPlayers();
    Gamerules getGamerules();
    GeneratorLeveling getGeneratorsLeveling();
    void setGeneratorsLeveling(GeneratorLeveling generatorLeveling);
    void setGamerules(Gamerules gamerules);
    HashMap<String, Team> getTeams();
    Integer getMaxInTeam();
    ArrayList<Generator> getGenerators();
    void addGenerator(Generator generator);
    ArrayList<Player> getSpectators();
    void addSpectator(Player player, boolean canExit);
    boolean joinAsSpectator(Player player);
    void createTeam(String name, ChatColor color);
    Team getTeam(String name);
    Team getTeam(Player player);
    List<TeamShop> getTeamShops();
    List<TeamUpgrades> getTeamUpgrades();
    Team getTeamByBed(Location bed);
    void changeSetup(Setup setup);
    Setup getSetupMode();
    ArrayList<UUID> getPlayersOnSetup();
    String getArenaName();
    void setMaxInTeam(Integer max);
    void setMinPlayers(Integer min);
    void setWaitingPos1(Location waitingPos1);
    void setWaitingPos2(Location waitingPos2);
    void setWaitingSpawn(Location waitingSpawn);
    void setWaitingTime(Integer time);
    void setRespawnTime(Integer time);
    void setSpecialGamerules(HashMap<String, Boolean> gamerules);
    void setSpecialGamerule(String gamerule, Boolean value);
    Location getWaitingSpawn();
    Integer getWaitingTime();
    Location getWaitingPos1();
    Location getWaitingPos2();
    void setQuickVoidY(int y);
    Integer getQuickVoidY();
    void bedDestruction();
    void endGame(String criteria);
    void enderDragonEnd();
    void enderDragonStart();
    void disableRegeneration();
    void disableTeamsForge();
    void addPlacedBlock(Location loc);
    boolean isPlacedBlock(Location loc);
    void clearPlacedBlocks();
    void addBlastProtBlock(Location loc);
    boolean isBlastProtBlock(Location loc);
    void removeBlastProtBlock(Location loc);
    String toJson();
}
